Repository pyiron/pyiron_base, pull requests merged in 2020-12, with the labels that each got.

#96 implement __repr__ in error
  pyiron_base/job/generic.py
  tests/job/test_genericJob.py
Labels: enhancement

#102 Correction from `if None` to `if None is not None`
  pyiron_base/server/generic.py
Labels: code_smell

#104 New docs + refactorings in JobGenerator
  pyiron_base/master/parallel.py
  tests/master/test_parallelmaster.py
Labels: documentation, enhancement

#118 Safe script path
  pyiron_base/job/script.py
  tests/job/test_script.py
Labels: code_smell

#119 enable delete_existing_job when job created via ref_job
  pyiron_base/job/generic.py
Labels: enhancement

#116 Add a util class for import warnings
  pyiron_base/generic/util.py
  tests/generic/test_util.py
Labels: enhancement
