Repository pyiron/pyiron_base, pull requests merged in 2020-10, with the labels that each got.

#61 Return publication list as pandas DataFrame
  pyiron_base/project/generic.py
  pyiron_base/settings/publications.py
Labels: enhancement

#62 Change queue_delete to call _queue_delete internally
  pyiron_base/job/core.py
  pyiron_base/project/generic.py
Labels: bug

#63 Pysqa update
  .ci_support/environment.yml
  setup.py
Labels: bug

#65 inhibit ragged list warning
  pyiron_base/generic/parameters.py
Labels: code_smell
