Repository pyiron/pyiron_base, pull requests merged in 2021-11, with the labels that each got.

#463 Save pyiron tables via DataContainer instead of csv
  pyiron_base/table/datamining.py
  tests/backwards/test_tablejob_load.py
  tests/backwards/test_tablejob_save.py
  tests/table/test_datamining.py
Labels: bug, enhancement

#494 Do not lose track of dtypes in get_array_ragged
  pyiron_base/generic/flattenedstorage.py
  tests/generic/test_flattenedstorage.py
Labels: bug

#488 Bugfix in case of None type values
  pyiron_base/master/serial.py
Labels: bug

#503 Correctly check for ragged array
  .github/workflows/benchmarks.yml
  pyiron_base/generic/hdfio.py
  test_benchmarks/__init__.py
  test_benchmarks/generic/__init__.py
  test_benchmarks/generic/test_filehdfio.py
  tests/generic/test_fileHDFio.py
Labels: bug

#512 Faster hdf reading
  pyiron_base/generic/hdfio.py
Labels: enhancement

#486 Refactor global state
  pyiron_base/__init__.py
  pyiron_base/_tests.py
  pyiron_base/archiving/import_archive.py
  pyiron_base/cli/install.py
  pyiron_base/cli/reloadfile.py
  pyiron_base/database/generic.py
  pyiron_base/database/jobtable.py
  pyiron_base/database/manager.py
  pyiron_base/database/performance.py
  pyiron_base/generic/object.py
  pyiron_base/generic/parameters.py
  pyiron_base/generic/util.py
  pyiron_base/job/core.py
  pyiron_base/job/generic.py
  pyiron_base/job/wrapper.py
  pyiron_base/master/parallel.py
  pyiron_base/project/generic.py
  pyiron_base/project/path.py
  pyiron_base/server/generic.py
  pyiron_base/server/queuestatus.py
  pyiron_base/settings/generic.py
  pyiron_base/settings/publications.py
  pyiron_base/state/__init__.py
  pyiron_base/state/install.py
  pyiron_base/state/logger.py
  pyiron_base/state/publications.py
  pyiron_base/state/queue_adapter.py
  pyiron_base/state/settings.py
  pyiron_base/state/update.py
  tests/database/test_manager.py
  tests/generic/test_singleton.py
  tests/job/test_script.py
  tests/settings/__init__.py
  tests/settings/test_generic.py
  tests/settings/test_generic_file_config.py
  tests/settings/test_generic_test_config.py
  tests/state/__init__.py
  tests/state/test_install.py
  tests/state/test_logger.py
  tests/state/test_publications.py
  tests/state/test_queue_adapter.py
  tests/state/test_settings.py
Labels: enhancement, code_smell

#511 Do not copy files on restart
  pyiron_base/_tests.py
  pyiron_base/job/generic.py
  tests/job/test_genericJob.py
Labels: code_smell

#523 Limit the timeout for windows workflows
  .github/workflows/atomistics-compat.yml
  .github/workflows/benchmarks.yml
  .github/workflows/unittests.yml
Labels: integration

#519 State hotfixes
  .github/workflows/contrib-compat.yml
  pyiron_base/database/manager.py
  pyiron_base/project/generic.py
  pyiron_base/state/settings.py
  tests/database/test_manager.py
  tests/project/test_projectPath.py
  tests/state/test_settings.py
Labels: integration

#534 Fix bug when writing empty FlattenedStorage
  pyiron_base/generic/flattenedstorage.py
  tests/generic/test_flattenedstorage.py
Labels: bug

#524 Refresh job status while waiting on project
  pyiron_base/server/queuestatus.py
Labels: enhancement

#544 Fix formatting in ImportAlarm docs
  pyiron_base/generic/util.py
Labels: documentation

#527 Do we need pytables?
  pyiron_base/job/core.py
Labels: integration

#541 Disable `project_check_enable` and retain `root_path`/`project_path`
  .github/workflows/notebooks.yml
  pyiron_base/database/manager.py
  pyiron_base/state/settings.py
  tests/database/test_manager.py
Labels: integration

#533 Fix writing ragged arrays & small update to update script
  pyiron_base/generic/hdfio.py
  tests/generic/test_fileHDFio.py
  update_scripts/pyiron_base_0.3_to_0.4.py
Labels: bug, enhancement

#556 Raise proper exceptions
  pyiron_base/job/jobstatus.py
  tests/job/test_jobStatus.py
Labels: bug

#555 Do not show job remove progress bar during unit tests
  pyiron_base/_tests.py
  pyiron_base/project/generic.py
Labels: enhancement, integration

#557 Add a method to draw a sample from a FlattenedStorage
  pyiron_base/generic/flattenedstorage.py
  tests/generic/test_flattenedstorage.py
Labels: enhancement

#528 Allow use of __getitem__/__setitem__ with FlattenedStorage
  pyiron_base/generic/flattenedstorage.py
  tests/generic/test_flattenedstorage.py
Labels: enhancement, integration

#558 Unleash mamba
  .github/workflows/atomistics-compat.yml
  .github/workflows/backwards.yml
  .github/workflows/benchmarks.yml
  .github/workflows/contrib-compat.yml
  .github/workflows/coverage.yml
  .github/workflows/docs.yml
  .github/workflows/notebooks.yml
  .github/workflows/old_python.yml
  .github/workflows/pypicheck.yml
  .github/workflows/unittests.yml
Labels: integration

#562 Allow default arguments to JobCore.get
  pyiron_base/job/core.py
Labels: enhancement, integration

#537 Allow custom return codes
  pyiron_base/job/executable.py
  pyiron_base/job/generic.py
  tests/job/test_genericJob.py
Labels: bug, enhancement, integration

#569 Migration to Python 3.10
  .github/workflows/atomistics-compat.yml
  .github/workflows/backwards.yml
  .github/workflows/benchmarks.yml
  .github/workflows/contrib-compat.yml
  .github/workflows/coverage.yml
  .github/workflows/deploy.yml
  .github/workflows/docs.yml
  .github/workflows/notebooks.yml
  .github/workflows/old_python.yml
  .github/workflows/pypicheck.yml
  .github/workflows/unittests.yml
  setup.py
  tests/generic/test_datacontainer.py
Labels: integration
