Repository pyiron/pyiron_base, pull requests merged in 2021-05, with the labels that each got.

#306 Add ipynb file support
  pyiron_base/generic/filedata.py
  pyiron_base/project/generic.py
  tests/generic/test_filedata.py
Labels: integration

#312 Use dill to save filter functions
  pyiron_base/table/datamining.py
  tests/table/__init__.py
  tests/table/test_datamining.py
Labels: enhancement, integration

#323 Project data hotfix
  pyiron_base/project/data.py
  pyiron_base/project/generic.py
  tests/project/test_data.py
Labels: bug

#314 Always add HDF5 file extension to path
  pyiron_base/generic/hdfio.py
  tests/generic/test_filedata.py
Labels: bug

#324 Remove obsolete ProjectStore
  pyiron_base/project/generic.py
  pyiron_base/project/store.py
Labels: enhancement, integration

#309 Change lookup order in JobCore.__getitem__
  pyiron_base/job/core.py
Labels: enhancement, integration

#328 Add method to manually trigger import warning
  pyiron_base/generic/util.py
Labels: enhancement

#320 Add hook after copy_to on Jobs
  pyiron_base/job/core.py
  pyiron_base/job/generic.py
  pyiron_base/master/generic.py
  pyiron_base/master/parallel.py
  tests/job/test_copyto.py
Labels: enhancement

#330 Pass original job to copy hook
  pyiron_base/job/generic.py
  pyiron_base/master/generic.py
  pyiron_base/master/parallel.py
Labels: bug
