Repository pyiron/pyiron_base, pull requests merged in 2021-09, with the labels that each got.

#340 Database Hotfix
  docs/source/installation.rst
  pyiron_base/database/generic.py
  pyiron_base/job/wrapper.py
  pyiron_base/settings/generic.py
  pyiron_base/settings/logger.py
Labels: bug

#427 Creator registration
  pyiron_base/__init__.py
  pyiron_base/job/factory.py
  pyiron_base/project/generic.py
  pyiron_base/toolkit.py
  tests/job/test_factory.py
  tests/project/test_project.py
  tests/test_toolkit.py
Labels: integration

#418 Script Job use Datacontainer for output
  pyiron_base/job/external.py
Labels: stale

#423 Add tqdm to Project.iter_jobs
  pyiron_base/project/generic.py
Labels: enhancement

#416 Add a Hdf mixin that takes care of type info + general boilerplate
  pyiron_base/generic/datacontainer.py
  pyiron_base/generic/hdfstub.py
  pyiron_base/interfaces/has_hdf.py
  tests/interfaces/__init__.py
  tests/interfaces/test_hashdf.py
Labels: enhancement

#433 Don't overwrite existing group in create_group
  pyiron_base/generic/datacontainer.py
  tests/generic/test_datacontainer.py
Labels: enhancement

#434 Smooth storage
  pyiron_base/generic/object.py
  pyiron_base/interfaces/has_hdf.py
  pyiron_base/job/template.py
Labels: enhancement, integration

#446 Use HasHDF in FlattenedStorage
  pyiron_base/generic/flattenedstorage.py
Labels: enhancement, integration

#452 Cleanup
  pyiron_base/job/generic.py
  pyiron_base/job/interactivewrapper.py
  pyiron_base/master/generic.py
Labels: integration

#453 Extract all database responsibilities from Settings
  pyiron_base/cli/reloadfile.py
  pyiron_base/database/manager.py
  pyiron_base/generic/object.py
  pyiron_base/job/generic.py
  pyiron_base/job/wrapper.py
  pyiron_base/master/parallel.py
  pyiron_base/project/generic.py
  pyiron_base/project/path.py
  pyiron_base/server/queuestatus.py
  pyiron_base/settings/generic.py
  pyiron_base/settings/update.py
  tests/database/test_manager.py
  tests/settings/test_generic_file_config.py
Labels: enhancement, integration

#455 More helpful error on invalid job name
  pyiron_base/job/util.py
Labels: documentation

#456 Integration tests
  .github/workflows/atomistics-compat.yml
  .github/workflows/contrib-compat.yml
Labels: integration

#454 Allow retrieving full flat arrays from get_array
  pyiron_base/generic/flattenedstorage.py
  tests/generic/test_flattenedstorage.py
Labels: enhancement
