Repository pyiron/pyiron_base, pull requests merged in 2021-12, with the labels that each got.

#571 Add copy, split and merge methods to FlattenedStorage
  pyiron_base/generic/flattenedstorage.py
  tests/generic/test_flattenedstorage.py
Labels: enhancement, integration

#595 Debug Interactive Open
  pyiron_base/job/interactive.py
  tests/job/test_job_interactive.py
Labels: integration

#495 Job factory call
  pyiron_base/job/factory.py
  pyiron_base/job/jobtype.py
  tests/job/test_factory.py
Labels: enhancement, integration

#594 Remove get_pandas
  pyiron_base/job/core.py
Labels: enhancement, integration

#593 Use notebook version of tqdm if possible
  pyiron_base/project/generic.py
  pyiron_base/table/datamining.py
  update_scripts/pyiron_base_0.3_to_0.4.py
Labels: enhancement
