Repository pyiron/pyiron_base, pull requests merged in 2021-06, with the labels that each got.

#338 Use input_only in GenericJob.copy_to
  pyiron_base/job/generic.py
Labels: bug, integration

#325 Move create pipeline
  pyiron_base/job/generic.py
Labels: bug, integration

#333 Add Interface for `list_nodes`/`list_groups`
  pyiron_base/generic/datacontainer.py
  pyiron_base/generic/hdfio.py
  pyiron_base/interfaces/__init__.py
  pyiron_base/interfaces/has_groups.py
  pyiron_base/job/core.py
  pyiron_base/job/generic.py
  pyiron_base/project/generic.py
  pyiron_base/table/datamining.py
  specs/has_groups.md
Labels: enhancement, stale

#346 Remove HDFStoreIO
  pyiron_base/generic/hdfio.py
Labels: enhancement, integration
