Repository pyiron/pyiron_base, pull requests merged in 2021-07, with the labels that each got.

#363 Use correct project in copy_to
  pyiron_base/master/generic.py
Labels: bug

#373 Properly cleanup copyto tests
  tests/job/test_copyto.py
Labels: enhancement

#375 Add FlattenedStorage from pyiron_contrib
  pyiron_base/__init__.py
  pyiron_base/generic/flattenedstorage.py
  tests/generic/test_flattenedstorage.py
Labels: enhancement

#372 Remove dead code
  pyiron_base/master/serial.py
Labels: enhancement, integration

#383 Fix per element/chunk confusion in FlattenedStorage.add_chunk
  pyiron_base/generic/flattenedstorage.py
  tests/generic/test_flattenedstorage.py
Labels: bug, integration

#387 Fix `read_only` in `DataContainer.from_hdf`
  pyiron_base/generic/datacontainer.py
  tests/generic/test_datacontainer.py
Labels: bug, integration

#379 Extend `load_file` to handle file objects.
  pyiron_base/generic/filedata.py
  tests/generic/test_filedata.py
Labels: enhancement, integration

#384 Enable to remove a job with loading the full job object.
  pyiron_base/job/core.py
Labels: integration
