Repository pyiron/pyiron_base, pull requests merged in 2021-03, with the labels that each got.

#187 Enhance file data handling
  pyiron_base/generic/filedata.py
  pyiron_base/project/generic.py
  tests/generic/test_filedata.py
Labels: enhancement

#237 Add workflow to run atomistic tests on push to master
  .github/workflows/atomistics-compat.yml
Labels: enhancement

#252 Input list patch
  pyiron_base/generic/datacontainer.py
  tests/generic/test_datacontainer.py
Labels: integration

#253 Six is no longer required
  .ci_support/environment.yml
Labels: integration

#216 Changes to InputList
  pyiron_base/__init__.py
  pyiron_base/generic/datacontainer.py
  pyiron_base/generic/fileio.py
  pyiron_base/generic/inputlist.py
  pyiron_base/job/script.py
  pyiron_base/project/data.py
  tests/generic/test_datacontainer.py
  tests/generic/test_fileio.py
  tests/generic/test_inputlist.py
Labels: integration

#259 Fix integration tests
  .github/workflows/atomistics-compat.yml
  .github/workflows/contrib-compat.yml
Labels: integration

#257 Migrate InputList to Datacontainer
  pyiron_base/__init__.py
  pyiron_base/generic/datacontainer.py
  pyiron_base/generic/fileio.py
  pyiron_base/generic/inputlist.py
  pyiron_base/job/script.py
  pyiron_base/project/data.py
  tests/generic/test_datacontainer.py
  tests/generic/test_fileio.py
  tests/generic/test_inputlist.py
Labels: integration

#262 Draft a test class parent
  pyiron_base/_tests.py
  tests/generic/test_datacontainer.py
  tests/job/test_genericJob.py
Labels: enhancement

#268 Make create_project_from_hdf5 public
  pyiron_base/generic/hdfio.py
  pyiron_base/job/generic.py
Labels: enhancement, integration

#210 Fix executable path for nested job classes
  pyiron_base/job/generic.py
Labels: integration

#271 Use test class filepath instead of parent class filepath
  pyiron_base/_tests.py
  tests/test_testwithproject.py
Labels: bug

#265 Add note about subclassing DataContainer
  pyiron_base/generic/datacontainer.py
Labels: documentation

#278 New TestWithCleanProject which removes jobs after each test
  pyiron_base/_tests.py
  tests/generic/test_datacontainer.py
  tests/generic/test_object.py
  tests/job/test_external.py
  tests/job/test_genericJob.py
  tests/job/test_script.py
  tests/job/test_scriptjob.py
  tests/test_testwithproject.py
Labels: integration
