Repository pyiron/pyiron_base, pull requests merged in 2021-08, with the labels that each got.

#388 Run integration test on linux, windows, and mac os (only python 3.9)
  .github/workflows/atomistics-compat.yml
Labels: integration

#394 Correct unpacking
  pyiron_base/archiving/export_archive.py
  pyiron_base/archiving/import_archive.py
  pyiron_base/project/generic.py
  tests/archiving/test_export.py
  tests/archiving/test_import.py
Labels: integration

#398 Allow filtering by job type
  pyiron_base/project/generic.py
Labels: enhancement, integration

#401 Install pyiron_base last in contrib compat workflow
  .github/workflows/contrib-compat.yml
Labels: bug, integration

#390 Strip first axis when creating array in add_chunk
  pyiron_base/generic/flattenedstorage.py
  tests/generic/test_flattenedstorage.py
Labels: bug, integration

#389 Fix HDF of FlattenedStorage
  pyiron_base/generic/flattenedstorage.py
  tests/generic/test_flattenedstorage.py
Labels: bug, integration

#397 A generic units class for pyiron
  .ci_support/environment.yml
  pyiron_base/_tests.py
  pyiron_base/generic/units.py
  tests/generic/test_units.py
Labels: enhancement

#410 Including pint
  .ci_support/environment.yml
  setup.py
Labels: dependencies

#415 Remove append from GenericJob
  pyiron_base/job/generic.py
Labels: enhancement, integration
