Repository pyiron/pyiron_base, pull requests merged in 2022-06, with the labels that each got.

#762 Move the logic of the run() function to a separate module
  pyiron_base/job/generic.py
  pyiron_base/job/runfunction.py
Labels: format_black

#763 Do not initialize Executable when none saved in HDF
  pyiron_base/job/generic.py
Labels: bug, format_black

#658 Draft automatic conversion to DataContainer
  pyiron_base/job/core.py
  pyiron_base/job/path.py
  tests/job/test_copyto.py
  tests/job/test_scriptjob.py
  tests/master/test_SerialMasterBase.py
Labels: bug, enhancement, integration, format_black
