Repository pyiron/pyiron_base, pull requests merged in 2022-11, with the labels that each got.

#884 hdfio: If the initial write fails with a BlockIOError try again after 1 second.
  pyiron_base/storage/hdfio.py
Labels: format_black

#901 Separate relocate_hdf
  pyiron_base/jobs/job/core.py
  pyiron_base/jobs/master/generic.py
Labels: enhancement, integration

#889 hdfio: If the initial write fails with a BlockIOError try again after 1 second.
  pyiron_base/database/filetable.py
  pyiron_base/jobs/job/generic.py
  pyiron_base/storage/hdfio.py
Labels: format_black

#882 Pyiron Table Refactor
  pyiron_base/jobs/datamining.py
Labels: documentation, enhancement, integration, format_black

#909 Add flattenedstorage to backwards compat list of class loading paths
  pyiron_base/storage/hdfio.py
Labels: bug

#914 Job docstrings
  pyiron_base/jobs/job/core.py
  pyiron_base/jobs/job/generic.py
  pyiron_base/jobs/master/flexible.py
  pyiron_base/jobs/master/generic.py
  pyiron_base/jobs/master/list.py
  pyiron_base/jobs/master/parallel.py
  pyiron_base/jobs/master/serial.py
Labels: format_black

#915 Pure python jobs do not need write_input()
  pyiron_base/jobs/datamining.py
  pyiron_base/jobs/master/generic.py
  pyiron_base/jobs/master/list.py
  pyiron_base/jobs/master/parallel.py
  pyiron_base/jobs/master/serial.py
  pyiron_base/jobs/worker.py
Labels: integration

#916 Implement a job.input for GenericMaster
  pyiron_base/jobs/job/generic.py
  pyiron_base/jobs/master/generic.py
  pyiron_base/jobs/master/list.py
  pyiron_base/jobs/master/parallel.py
  pyiron_base/jobs/master/serial.py
Labels: format_black

#925 Accept both GenericParameters or DataContainer as input
  pyiron_base/jobs/master/generic.py
Labels: integration

#927 Move __getitem__() to GenericMaster
  pyiron_base/jobs/master/flexible.py
  pyiron_base/jobs/master/generic.py
  pyiron_base/jobs/master/interactivewrapper.py
  pyiron_base/jobs/master/list.py
  pyiron_base/jobs/master/parallel.py
  pyiron_base/jobs/master/serial.py
Labels: integration
