Repository pyiron/pyiron_base, pull requests merged in 2022-04, with the labels that each got.

#739 Fix Job Factory
  pyiron_base/job/factory.py
Labels: integration

#717 Extension of the dynamic job class to support external executables
  pyiron_base/generic/dynamic.py
Labels: stale

#742 Fix typo in HasHDF example
  pyiron_base/interfaces/has_hdf.py
Labels: documentation

#744 Check that args.project exists first before removing in cli.rm
  pyiron_base/cli/rm.py
Labels: bug
