Repository pyiron/pyiron_base, pull requests merged in 2022-12, with the labels that each got.

#888 Set new job name when copying db entry
  pyiron_base/jobs/job/util.py
  tests/job/test_copyto.py
  tests/job/test_genericJob.py
Labels: bug, integration

#929 Add a function that retries some operation until no exception is thrown
  pyiron_base/database/generic.py
  pyiron_base/storage/hdfio.py
  pyiron_base/utils/error.py
  tests/utils/__init__.py
  tests/utils/test_error.py
Labels: bug, enhancement, integration, format_black

#934 refresh_job_status also for submitted jobs
  pyiron_base/project/generic.py
  tests/job/test_worker.py
Labels: enhancement

#875 Adds a job.kill() functionality that stops a job in the queueing system without removal of files and updates status.
  pyiron_base/jobs/job/core.py
  pyiron_base/jobs/job/generic.py
  pyiron_base/jobs/job/runfunction.py
Labels: format_black

#943 Fix the flexible master
  pyiron_base/jobs/master/flexible.py
Labels: integration

#947 Fix pytable warning
  pyiron_base/database/generic.py
Labels: integration

#944 Correct type hinting for job name sanitizer
  pyiron_base/jobs/job/util.py
Labels: format_black

#948 Disable working directory warining
  .ci_support/pyironconfig.py
  pyiron_base/state/settings.py
Labels: format_black

#958 Merge JobPath & JobPathCore
  pyiron_base/jobs/job/path.py
  pyiron_base/project/generic.py
Labels: integration, format_black

#812 Add Project.symlink method to move and replace a project by symlink elsewhere
  pyiron_base/project/generic.py
  tests/project/test_project.py
Labels: enhancement, format_black
