Repository pyiron/pyiron_base, pull requests merged in 2022-07, with the labels that each got.

#783 Allow to `delete_existing_job` if it has no `job_id`
  pyiron_base/_tests.py
  pyiron_base/job/generic.py
  tests/job/test_genericJob.py
Labels: format_black

#794 Fix job type register
  pyiron_base/job/generic.py
  pyiron_base/job/jobtype.py
  tests/job/test_jobtype.py
Labels: integration

#795 Hotfix for pack/unpack: Add flag to include all files in jobs
  pyiron_base/archiving/export_archive.py
  pyiron_base/project/generic.py
Labels: enhancement, format_black

#801 Refactor #799
  pyiron_base/jobs/job/jobtype.py
Labels: format_black
