Repository pyiron/pyiron_base, pull requests merged in 2022-01, with the labels that each got.

#618 Introduce black formatting workflow triggered by `format_black` label
  .github/workflows/format_black.yml
Labels: format_black

#635 Specify units for memory limit
  pyiron_base/server/generic.py
Labels: documentation

#647 Mention wrong column name in error message
  pyiron_base/database/generic.py
Labels: bug

#645 Set default project for WorkerJob
  pyiron_base/job/worker.py
Labels: bug

#609 [ci skip] Update Documentation - Pyiron release chapter
  .github/workflows/UpdateDependabotPR.yml
  .github/workflows/atomistics-compat.yml
  .github/workflows/backwards.yml
  .github/workflows/benchmarks.yml
  .github/workflows/black.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/contrib-compat.yml
  .github/workflows/coverage.yml
  .github/workflows/deploy.yml
  .github/workflows/docs.yml
  .github/workflows/notebooks.yml
  .github/workflows/pypicheck.yml
  .github/workflows/unittests.yml
  CONTRIBUTING.rst
Labels: documentation, good first issue, help wanted

#656 Add descriptions to PyironTable progress bars
  pyiron_base/table/datamining.py
Labels: enhancement

#644 Always write error.out
  pyiron_base/job/generic.py
Labels: bug, format_black

#631 Get filesize of Project
  pyiron_base/project/generic.py
Labels: format_black
