Repository pyiron/pyiron_base, pull requests merged in 2022-08, with the labels that each got.

#819 ignore non-pyiron HDF5 files
  pyiron_base/database/filetable.py
Labels: format_black

#820 Filetable: Define column names only once
  pyiron_base/database/filetable.py
Labels: format_black

#806 Outsource credential information to own config file
  pyiron_base/state/settings.py
  tests/state/test_settings.py
Labels: enhancement

#813 Add tqdm bars to Project.{copy_to,move_to}
  pyiron_base/project/generic.py
Labels: enhancement, integration

#833 Avoid unnecessary copy in FlattenedStorage._from_hdf
  pyiron_base/storage/flattenedstorage.py
Labels: enhancement
