Repository pyiron/pyiron_base, pull requests merged in 2022-03, with the labels that each got.

#721 Fix formatting strings in server debug messages
  pyiron_base/server/generic.py
Labels: format_black

#723 Adding to install dialog
  pyiron_base/state/install.py
Labels: format_black

#729 Update DataContainer example to use HasStorage
  pyiron_base/generic/datacontainer.py
Labels: documentation

#730 Allow inverted matches in job queries
  pyiron_base/database/generic.py
  tests/project/test_project.py
Labels: enhancement, dependencies, format_black

#734 Check covergence for parallel masters
  pyiron_base/master/parallel.py
  tests/master/test_parallelmaster.py
Labels: enhancement

#735 Do not truncate identifier strings in FlattenedStorage
  pyiron_base/generic/flattenedstorage.py
  tests/generic/test_flattenedstorage.py
Labels: enhancement, format_black
