Repository pyiron/pyiron_base, pull requests merged in 2022-10, with the labels that each got.

#843 Add warning file to working directories
  pyiron_base/_tests.py
  pyiron_base/jobs/datamining.py
  pyiron_base/jobs/dynamic.py
  pyiron_base/jobs/job/core.py
  pyiron_base/jobs/job/generic.py
  pyiron_base/jobs/master/flexible.py
  pyiron_base/jobs/master/list.py
  pyiron_base/jobs/master/parallel.py
  pyiron_base/jobs/master/serial.py
  pyiron_base/jobs/script.py
  pyiron_base/state/settings.py
  tests/job/test_genericJob.py
Labels: integration, format_black

#850 Add additional exceptions to HDF access fast path
  pyiron_base/storage/hdfio.py
Labels: bug

#851 Update iter_jobs docstring
  pyiron_base/project/generic.py
Labels: format_black

#852 Fix ridiculous typo
  pyiron_base/jobs/job/core.py
Labels: bug, integration

#873 add docstring to pyiron table
  pyiron_base/jobs/datamining.py
Labels: format_black

#878 Queue table compatible to File table
  pyiron_base/jobs/job/extension/server/queuestatus.py
  pyiron_base/project/generic.py
Labels: format_black

#862 A (HasTraits, HasStorage)-based data class
  .ci_support/environment-docs.yml
  .ci_support/environment.yml
  pyiron_base/__init__.py
  pyiron_base/storage/has_stored_traits.py
  setup.py
  tests/storage/__init__.py
  tests/storage/test_has_stored_traits.py
Labels: enhancement, dependencies
