Repository pyiron/pyiron_base, pull requests merged in 2022-02, with the labels that each got.

#668 Fix off-by-one in FlattenedStorage
  pyiron_base/generic/flattenedstorage.py
  tests/generic/test_flattenedstorage.py
Labels: bug

#655 Add progress bar to Project.iter_groups
  pyiron_base/project/generic.py
Labels: enhancement

#674 Remove project reference in FileHDFio
  pyiron_base/generic/hdfio.py
  tests/generic/test_fileHDFio.py
Labels: bug, integration

#681 pyiron without database: Reduce need to build file table
  pyiron_base/job/core.py
  pyiron_base/job/generic.py
  pyiron_base/job/worker.py
  tests/database/test_no_database_project.py
Labels: integration

#706 Clean up job_type class loading
  pyiron_base/job/jobtype.py
Labels: integration
