Repository pyiron/pyiron_base, pull requests merged in 2023-02, with the labels that each got.

#1019 Back to mappings
  pyiron_base/database/generic.py
  tests/database/test_database_access.py
Labels: format_black

#1012 job_table: Check for str before checking for character
  pyiron_base/database/generic.py
Labels: bug

#1027 Tell user to restart server when pyiron install ends
  pyiron_base/state/install.py
Labels: enhancement

#1030 fix pyiron_atomistics project level create_job()
  pyiron_base/jobs/job/generic.py
  pyiron_base/storage/hdfio.py
Labels: format_black

#1035 Clean `generic.py` and `core.py` - part 1
  pyiron_base/jobs/job/core.py
  pyiron_base/jobs/job/generic.py
Labels: integration

#1036 Clean `generic.py` and `core.py` - part 2
  pyiron_base/jobs/job/generic.py
  pyiron_base/jobs/job/runfunction.py
Labels: integration

#1042 Use safe __getitem__() to enable reloading jobs with special characters like spaces
  pyiron_base/project/generic.py
Labels: integration

#1047 project pack raise warning when destination_path matches project path
  pyiron_base/project/generic.py
Labels: format_black
