Repository pyiron/pyiron_base, pull requests merged in 2023-12, with the labels that each got.

#1162 Add an interface to turn objects read-only
  pyiron_base/interfaces/lockable.py
  pyiron_base/jobs/job/extension/server/generic.py
  pyiron_base/jobs/job/generic.py
  pyiron_base/jobs/master/generic.py
  pyiron_base/jobs/master/interactivewrapper.py
  pyiron_base/jobs/script.py
  pyiron_base/storage/datacontainer.py
  tests/generic/test_datacontainer.py
Labels: enhancement, integration, format_black

#1164 Switch from dill to cloudpickle
  .ci_support/environment-old.yml
  .ci_support/environment.yml
  pyiron_base/jobs/datamining.py
  pyproject.toml
  tests/backwards/test_dill_cloudpickle_compatibility.py
Labels: help wanted, format_black

#1250 GenericJob: add to_dict() and from_dict()
  pyiron_base/jobs/job/generic.py
Labels: format_black

#1247 HDF5 interface: add write_dict_to_hdf() and read_dict_from_hdf()
  .ci_support/environment-old.yml
  pyiron_base/storage/hdfio.py
  pyiron_base/storage/helper_functions.py
Labels: format_black

#1249 GenericParameters: add to_dict() and from_dict()
  pyiron_base/interfaces/has_dict.py
  pyiron_base/interfaces/has_hdf.py
  pyiron_base/jobs/job/generic.py
  pyiron_base/storage/parameters.py
Labels: format_black

#1266 Revert "DataContainer: split _to_hdf() "
  pyiron_base/storage/datacontainer.py
Labels: integration, format_black

#1269 Fix compatibility with atomistics
  .github/workflows/atomistics-compat.yml
Labels: integration
