Repository pyiron/pyiron_base, pull requests merged in 2023-06, with the labels that each got.

#1111 fix for missing pyironconfig in contrib
  .github/workflows/contrib-compat.yml
Labels: integration

#1115 HasStoredTraits: Use setitem instead of setattr
  pyiron_base/storage/has_stored_traits.py
Labels: bug

#1113 Do not try to double write objects that define to_hdf
  pyiron_base/storage/hdfio.py
Labels: bug

#1101 Polish filetable
  pyiron_base/database/filetable.py
  tests/database/test_filetable.py
Labels: format_black

#1112 Only try to lock Traits objects
  pyiron_base/storage/has_stored_traits.py
Labels: enhancement, format_black

#1119 Runmode manually: Fix message when run without database
  pyiron_base/jobs/job/runfunction.py
Labels: format_black

#1121 Move all run functions to separate module
  pyiron_base/jobs/job/generic.py
  pyiron_base/jobs/job/runfunction.py
Labels: format_black

#1123 Queue status
  pyiron_base/jobs/job/extension/server/queuestatus.py
  pyiron_base/jobs/job/runfunction.py
Labels: format_black

#1133 Add numpy equality check for unit tests
  pyiron_base/_tests.py
  tests/database/test_filetable.py
  tests/generic/test_datacontainer.py
  tests/generic/test_fileHDFio.py
  tests/generic/test_flattenedstorage.py
  tests/generic/test_util.py
  tests/project/test_data.py
  tests/project/test_project.py
  tests/server/test_server.py
  tests/state/test_settings.py
  tests/storage/test_has_stored_traits.py
  tests/table/test_datamining.py
Labels: enhancement, format_black

#1141 Revert flux introduction
  pyiron_base/jobs/job/extension/server/runmode.py
  pyiron_base/jobs/job/generic.py
  pyiron_base/jobs/job/runfunction.py
Labels: integration

#1139 FileTable on windows
  pyiron_base/database/filetable.py
  tests/database/test_filetable.py
Labels: integration

#1138 Check if project path exists before creating Project
  pyiron_base/jobs/datamining.py
  tests/table/test_datamining.py
Labels: format_black

#1148 Drop pathlib2
  .ci_support/environment-docs.yml
  .ci_support/environment.yml
  pyiron_base/project/external.py
  setup.py
Labels: dependencies, integration

#1149 Add method to delete arrays from FlattenedStorage
  pyiron_base/storage/flattenedstorage.py
  tests/generic/test_flattenedstorage.py
Labels: enhancement
