Repository pyiron/pyiron_base, pull requests merged in 2023-01, with the labels that each got.

#987 Split execute_job_with_external_executable() into multiple sub functions
  pyiron_base/jobs/job/extension/executable.py
  pyiron_base/jobs/job/runfunction.py
Labels: format_black

#980 Call the correct logging method
  pyiron_base/database/manager.py
Labels: bug, integration, format_black

#988 Remove relative imports for cli
  pyiron_base/cli/__init__.py
  pyiron_base/cli/__main__.py
  pyiron_base/cli/control.py
Labels: format_black

#995 set self._hdf5 only when ProjectHDF comes
  pyiron_base/jobs/job/generic.py
Labels: enhancement, integration

#971 Dont fetch waiting jobs
  pyiron_base/database/filetable.py
  pyiron_base/database/generic.py
  pyiron_base/jobs/job/extension/server/queuestatus.py
  pyiron_base/jobs/job/generic.py
  pyiron_base/project/generic.py
  pyiron_base/storage/hdfio.py
  pyiron_base/storage/helper_functions.py
Labels: integration, format_black

#967 Move signal catching to separate module and refactor
  pyiron_base/jobs/job/generic.py
  pyiron_base/state/signal.py
Labels: integration, format_black

#1004 Set maxtasksperchild for worker class
  pyiron_base/jobs/worker.py
Labels: format_black

#1000 Cleaner tests
  pyiron_base/_tests.py
  tests/archiving/test_export.py
  tests/archiving/test_import.py
  tests/database/test_database_file.py
  tests/database/test_no_database_project.py
  tests/generic/test_fileHDFio.py
  tests/generic/test_genericParameters.py
  tests/job/test_databaseproperties.py
  tests/job/test_genericJob.py
  tests/job/test_interactivewrapper.py
  tests/job/test_jobtypechoice.py
  tests/project/test_genericPath.py
  tests/project/test_projectPath.py
  tests/server/test_runmode.py
Labels: integration

#1010 Uniform database access to get child ids
  pyiron_base/database/filetable.py
  pyiron_base/jobs/job/core.py
Labels: format_black
