Repository pyiron/pyiron_base, pull requests merged in 2024-02, with the labels that each got.

#1304 Fix read_dict_from_hdf() when using overlapping paths
  pyiron_base/storage/helper_functions.py
  tests/storage/test_helper_functions.py
Labels: format_black

#1308 No longer require functions for create_job_factory()
  pyiron_base/jobs/flex/executablecontainer.py
  pyiron_base/jobs/flex/factory.py
  pyiron_base/project/generic.py
  tests/flex/test_executablecontainer.py
Labels: format_black

#1313 Do not import sqlalchemy when running without database
  pyiron_base/__init__.py
  pyiron_base/database/filetable.py
  pyiron_base/database/generic.py
  pyiron_base/database/interface.py
  pyiron_base/database/manager.py
  pyiron_base/jobs/job/extension/jobstatus.py
  pyiron_base/jobs/master/submissionstatus.py
  pyiron_base/project/generic.py
  pyiron_base/storage/hdfio.py
Labels: format_black

#1309 Accelerate import of pyiron_base by 18%
  pyiron_base/__init__.py
  pyiron_base/project/generic.py
Labels: format_black

#1314 Do not import pint when it is not needed
  pyiron_base/project/generic.py
  pyiron_base/project/size.py
  tests/project/test_project.py
Labels: format_black

#1311 Add output files class
  .ci_support/environment-docs.yml
  .ci_support/environment-old.yml
  .ci_support/environment.yml
  pyiron_base/jobs/job/core.py
  pyiron_base/jobs/job/extension/files.py
  pyiron_base/jobs/job/util.py
  pyproject.toml
  tests/flex/test_executablecontainer.py
  tests/job/test_genericJob.py
Labels: format_black

#1315 Execute jobs in separate conda environments
  .ci_support/environment.yml
  pyiron_base/jobs/job/extension/server/generic.py
  pyiron_base/jobs/job/runfunction.py
  pyiron_base/project/condaenv.py
  pyiron_base/project/generic.py
  pyproject.toml
  tests/flex/test_executablecontainer_conda.py
  tests/job/test_jobtype.py
Labels: format_black

#1332 Refactor database interface
  pyiron_base/project/generic.py
Labels: format_black

#1324 remove unnecessary database queries
  pyiron_base/project/generic.py
Labels: format_black

#1336 Fix regression on #1188
  pyiron_base/storage/hdfio.py
Labels: bug

#1337 Do not fail hdf type update if project data missing
  pyiron_base/project/maintenance.py
Labels: bug

#1334 Use the same executor for pyiron table and function container
  .ci_support/environment-docs.yml
  .ci_support/environment-old.yml
  .ci_support/environment.yml
  pyiron_base/jobs/datamining.py
  pyiron_base/jobs/flex/pythonfunctioncontainer.py
  pyiron_base/jobs/job/generic.py
  pyiron_base/utils/instance.py
  pyproject.toml
  tests/flex/test_pythonfunctioncontainer.py
  tests/table/test_datamining.py
Labels: format_black

#1343 Try to access files after HDF
  pyiron_base/jobs/job/core.py
Labels: performance

#1262 Purge SerialMaster
  pyiron_base/__init__.py
  pyiron_base/jobs/job/factory.py
  pyiron_base/jobs/job/generic.py
  pyiron_base/jobs/job/interactive.py
  pyiron_base/jobs/job/jobtype.py
  pyiron_base/jobs/master/serial.py
  pyiron_base/jobs/script.py
  pyiron_base/project/generic.py
  tests/job/test_copyto.py
  tests/job/test_jobtype.py
  tests/master/test_SerialMasterBase.py
Labels: integration

#1299 Split DataContainer to a HDF and non HDF part
  pyiron_base/storage/datacontainer.py
  tests/generic/test_datacontainer.py
Labels: integration, format_black
