Repository pyiron/pyiron_base, pull requests merged in 2024-07, with the labels that each got.

#1508 Delayed execution in pyiron_base - for wrap_python_function() and wrap_executable()
  pyiron_base/jobs/flex/pythonfunctioncontainer.py
  pyiron_base/project/delayed.py
  pyiron_base/project/generic.py
  tests/flex/test_executablecontainer.py
  tests/flex/test_pythonfunctioncontainer.py
Labels: format_black

#1513 Executable: drop old code argument
  pyiron_base/jobs/job/extension/executable.py
Labels: integration

#1335 Fix multi dimensional arrays with FlattenedStorage.to_pandas
  pyiron_base/_tests.py
  pyiron_base/storage/flattenedstorage.py
  tests/unit/storage/test_flattenedstorage.py
Labels: bug

#1543 [patch] Remove redundant conversion of project name
  pyiron_base/project/archiving/export_archive.py
  pyiron_base/project/generic.py
Labels: patch

#1544 [patch] Refactor compress dir
  pyiron_base/project/archiving/export_archive.py
Labels: patch

#1549 Use `copytree` in `pack`
  pyiron_base/project/archiving/export_archive.py
Labels: enhancement, format_black, patch

#1551 Restore sub directories
  pyiron_base/project/archiving/export_archive.py
  tests/unit/archiving/test_export.py
Labels: bug, patch

#1550 Refactor and add doc string (done by ChatGPT)
  pyiron_base/project/archiving/export_archive.py
Labels: format_black, patch

#1555 [patch] Use `tempfile` instead of creating a directory
  tests/unit/archiving/test_export.py
Labels: code_smell, patch

#1562 Add deprecate warnings when indexing jobs directly
  pyiron_base/jobs/job/core.py
  pyiron_base/jobs/master/generic.py
Labels: integration, format_black

#1571 delete extraction function because it became very short and give an e…
  pyiron_base/project/archiving/import_archive.py
  tests/unit/archiving/test_import.py
Labels: patch
