Repository pyiron/pyiron_base, pull requests merged in 2024-01, with the labels that each got.

#1271 Use h5io_browser package
  .ci_support/environment-old.yml
  .ci_support/environment.yml
  pyiron_base/jobs/job/generic.py
  pyiron_base/storage/hdfio.py
  pyiron_base/storage/helper_functions.py
  pyproject.toml
  tests/project/test_maintenance.py
  tests/storage/test_fileHDFio.py
  tests/storage/test_helper_functions.py
Labels: integration

#1273 Use _read_hdf() and _write_hdf() from h5io_browser
  pyiron_base/database/filetable.py
  pyiron_base/jobs/job/generic.py
  pyiron_base/storage/hdfio.py
  pyiron_base/storage/helper_functions.py
  tests/storage/test_helper_functions.py
Labels: integration, format_black

#1272 Avoid repetitions in job_table
  pyiron_base/project/generic.py
Labels: enhancement, integration

#1287 Remove dynamic jobs
  pyiron_base/__init__.py
  pyiron_base/jobs/dynamic.py
  pyiron_base/jobs/job/jobtype.py
  pyiron_base/storage/hdfio.py
  tests/job/test_dynamic.py
Labels: integration, format_black

#1276 [feedback wanted] Use regex for job table sorting
  pyiron_base/database/generic.py
  pyiron_base/project/generic.py
  tests/project/test_project.py
Labels: enhancement, format_black

#1297 Update Documentation
  .ci_support/environment-docs.yml
  .github/workflows/dependabot.yml
  .github/workflows/docs.yml
  .readthedocs.yml
  docs/Makefile
  docs/_static/pyiron-logo.png
  docs/_static/pyiron_logo.ico
  docs/_static/screenshot.png
  docs/_static/screenshots.png
  docs/conf.py
  docs/index.rst
  docs/make.bat
  docs/make.py
  docs/make.sh
  docs/make_apidoc.bat
  docs/source/about.rst
  docs/source/commandline.md
  docs/source/commandline.rst
  docs/source/conf.py
  docs/source/developer.md
  docs/source/example.md
  docs/source/examples.rst
  docs/source/faq.md
  docs/source/faq.rst
  docs/source/hdf5.rst
  docs/source/index.rst
  docs/source/indices.rst
  docs/source/installation.md
  docs/source/installation.rst
  docs/source/notebooks/pyiron_paper.ipynb
  docs/source/notebooks/pythonjobtemplate.ipynb
  docs/source/queue_submit_flow.md
  docs/source/tutorial.md
  pyiron_base/_tests.py
  pyiron_base/database/generic.py
  pyiron_base/jobs/job/runfunction.py
  pyiron_base/project/archiving/export_archive.py
  pyiron_base/project/jobloader.py
  pyiron_base/project/update/pyiron_base_03x_to_04x.py
  pyiron_base/state/settings.py
  pyiron_base/storage/datacontainer.py
  pyiron_base/storage/filedata.py
  pyiron_base/storage/fileio.py
  pyiron_base/storage/flattenedstorage.py
Labels: format_black
