Repository pyiron/pyiron_base, pull requests merged in 2024-06, with the labels that each got.

#1468 Fix typo in HDF5Content recursive loading
  pyiron_base/jobs/job/core.py
  tests/job/test_hdf5content.py
Labels: bug, format_black

#1474 Reorder return values from handle_failed_job
  pyiron_base/jobs/job/runfunction.py
Labels: bug

#1480 Scriptjob implement calculate() function
  pyiron_base/jobs/script.py
Labels: format_black

#1477 Introduce calculate() function
  pyiron_base/jobs/datamining.py
  pyiron_base/jobs/flex/executablecontainer.py
  pyiron_base/jobs/job/generic.py
  pyiron_base/jobs/job/runfunction.py
  pyiron_base/jobs/job/template.py
  pyiron_base/jobs/master/generic.py
  pyiron_base/jobs/script.py
  pyiron_base/jobs/worker.py
  tests/job/test_genericJob.py
Labels: format_black
