Repository pyiron/pyiron_base, pull requests merged in 2024-03, with the labels that each got.

#1365 Add Lockable to FlattenedStorage
  pyiron_base/storage/flattenedstorage.py
Labels: enhancement

#1358 [minor] Opt in hash for pythonfunction
  pyiron_base/jobs/flex/pythonfunctioncontainer.py
  pyiron_base/project/generic.py
  tests/flex/test_pythonfunctioncontainer.py
Labels: format_black

#1391 Move recursive loading of DataContainer to HDF5Content
  pyiron_base/jobs/job/core.py
  tests/job/test_hdf5content.py
Labels: integration

#1392 Misc FileBrowser features
  pyiron_base/jobs/job/extension/files.py
  tests/flex/test_executablecontainer.py
  tests/job/test_genericJob.py
Labels: Feature request, format_black

#1396 Database: Extend job_name and project_path to 255 characters
  pyiron_base/database/generic.py
  pyiron_base/database/sqlcolumnlength.py
  pyiron_base/database/tables.py
  pyiron_base/jobs/job/util.py
  pyiron_base/state/update.py
Labels: format_black

#1379 Datamining: Use to_dict() and from_dict()
  pyiron_base/jobs/datamining.py
Labels: format_black

#1377 Executable: Switch from HasHDF to HasDict
  pyiron_base/jobs/job/extension/executable.py
  pyiron_base/jobs/job/generic.py
  tests/flex/test_executablecontainer.py
Labels: format_black

#1380 job.server: remove to_hdf() and from_hdf()
  pyiron_base/jobs/job/extension/server/generic.py
  pyiron_base/jobs/job/runfunction.py
  tests/server/test_server.py
Labels: format_black

#1372 Extend conda interface: store conda environments in project
  pyiron_base/project/condaenv.py
  pyiron_base/project/generic.py
  tests/flex/test_executablecontainer_conda.py
Labels: format_black
