Repository pyiron/pyiron_base, pull requests merged in 2024-08, with the labels that each got.

#1570 Use tempfile
  pyiron_base/project/archiving/export_archive.py
  pyiron_base/project/generic.py
  tests/unit/archiving/test/nested/imported/test/toy.h5
Labels: code_smell, minor

#1583 Add docstring to import jobs
  pyiron_base/project/archiving/import_archive.py
Labels: patch

#1581 Allow undefined pack destination
  pyiron_base/project/generic.py
  tests/unit/archiving/test_export.py
Labels: enhancement, minor

#1582 Only create temp_dir when compress=True
  pyiron_base/project/archiving/export_archive.py
Labels: format_black, patch

#1590 not use relpath by default
  pyiron_base/project/archiving/export_archive.py
  pyiron_base/project/generic.py
Labels: format_black, minor

#1596 [patch] Add warning when the same job is imported multiple times with `unpack`
  pyiron_base/database/generic.py
  pyiron_base/project/archiving/import_archive.py
Labels: code_smell, patch

#1598 [patch] Unify `copy_to` and `move_to`
  pyiron_base/project/generic.py
Labels: enhancement, patch

#1599 [patch] Append tag when patch, minor or major is added
  .github/workflows/label-to-title.yml
Labels: enhancement, patch

#1595 [patch] Restructure archive
  pyiron_base/project/archiving/export_archive.py
  pyiron_base/project/archiving/import_archive.py
  pyiron_base/project/generic.py
  tests/unit/archiving/test_export.py
  tests/unit/archiving/test_import.py
Labels: patch

#1589 [patch] Not create tmp file when copying everything
  pyiron_base/project/archiving/export_archive.py
  tests/unit/archiving/test_import.py
Labels: patch

#1558 [patch] Use tempfile instead of creating a directory
  tests/unit/archiving/test_export.py
Labels: format_black

#1601 [patch] Use tempfile to open compressed data
  pyiron_base/project/archiving/import_archive.py
Labels: patch

#1440 [minor] Update pack and unpack methods
  notebooks/import_export_example.ipynb
  pyiron_base/project/archiving/export_archive.py
  pyiron_base/project/archiving/import_archive.py
  pyiron_base/project/archiving/shared.py
  pyiron_base/project/generic.py
  tests/unit/archiving/test_export.py
  tests/unit/archiving/test_import.py
Labels: minor

#1602 [minor] Recursive to/from_dict
  pyiron_base/interfaces/has_dict.py
  pyiron_base/jobs/datamining.py
  pyiron_base/jobs/flex/executablecontainer.py
  pyiron_base/jobs/flex/pythonfunctioncontainer.py
  pyiron_base/jobs/job/extension/executable.py
  pyiron_base/jobs/job/extension/server/generic.py
  pyiron_base/jobs/job/generic.py
  pyiron_base/jobs/job/template.py
  pyiron_base/jobs/script.py
  pyiron_base/storage/datacontainer.py
  pyiron_base/storage/parameters.py
  tests/unit/server/test_server.py
Labels: enhancement, integration, minor

#1364 Add two classes for HasHDF/HasDict compat
  pyiron_base/interfaces/has_dict.py
  pyiron_base/interfaces/has_hdf.py
  pyiron_base/jobs/datamining.py
  pyiron_base/jobs/flex/executablecontainer.py
  pyiron_base/jobs/flex/pythonfunctioncontainer.py
  pyiron_base/jobs/job/extension/executable.py
  pyiron_base/jobs/job/extension/server/generic.py
  pyiron_base/jobs/job/generic.py
  pyiron_base/jobs/job/template.py
  pyiron_base/jobs/script.py
  pyiron_base/storage/datacontainer.py
  pyiron_base/storage/flattenedstorage.py
  pyiron_base/storage/hdfio.py
  pyiron_base/storage/hdfstub.py
  pyiron_base/storage/parameters.py
  tests/unit/generic/test_datacontainer.py
  tests/unit/server/test_server.py
Labels: enhancement, integration, format_black

#1617 [patch] Add pack backwards compatibility tests
  tests/static/pack/export.csv
  tests/static/pack/test_pack.tar.gz
  tests/unit/archiving/test_import.py
Labels: patch
